### ISSUE TITLE
Adafruit Trinket M0 plays sine1kHz but not other examples

### ISSUE THREAD

**Issue by fergbrain** [ocrdu/Arduino_SAMD21_Audio_Player#1]
Using an Trinket M0 (which is an SAMD21) I can play the sine1kHz array just fine.

However, neither HAL nor Eurythmics plays.

I tried truncating HAL to be the same size as sine1kHz, but that doesn't work either.

Looking at the oscilliscope I also don't see anything resembling a waveform. Pin A0 appears to either be in HIGH or LOW, nothing in between (as you would expect for DAC).

Not sure what else I can do to troubleshoot. Thoughts?

**Comment by ocrdu** [comment]
That's weird; all it does is send bytes to the DAC; shouldn't matter what bytes. 

The only real difference for this between the Nano 33 IoT I tested this on and the Trinket M0 is that the former has a SAMD21G MCU, and the latter has a SAMD21E MCU, but according to the datasheet they are supposed to have the same DAC on the same pin.

I don't have a Trinket M0 for testing, but I'll look into it.

**Comment by fergbrain** [comment]
According to https://www.arduino.cc/reference/en/language/functions/analog-io/analogwrite/ and https://learn.adafruit.com/adafruit-trinket-m0-circuitpython-arduino/adapting-sketches-to-m0 the M0 uses the DAC for true analog out, not PWM, when analogWrite is used.

However, one thing I noticed doing my own testing with just using analogWrite is that values above 150 or so (I'll need to double check when I get home) don't output at all on A0 (Pin 1). However, Pin 0 (which is A2) does get digital HIGH...so I'm thinking it's related to that. 

The adafruit notes (https://learn.adafruit.com/adafruit-trinket-m0-circuitpython-arduino/adapting-sketches-to-m0#analogwrite-dac-on-a0-3008984-8) say to *not* do `pinMode(A0, OUTPUT)...so I need to make sure I wasn't doing that.
`

There's also a usage note on timers that may impact your code, I'll have to dig into that deeper too (though it's probably a bit over my head): https://learn.adafruit.com/adafruit-trinket-m0-circuitpython-arduino/adapting-sketches-to-m0#analogwrite-slash-pwm-on-feather-slash-metro-m0-2677095-6

I'll update you with what I find.

**Comment by fergbrain** [comment]
I hooked up a piezo earpiece and confirmed that your code works as-is. I think the issue I was having with the o-scope is that I was using the same setting for the sine wav, which has a much higher peak-to-peak, so playing one of the other examples just looked like noise.

I've ordered an amplifier so I can directly drive an external 8ohm speaker.
