### ISSUE TITLE
Play samples from SPI Flash memory ?

### ISSUE THREAD

**Issue by janczeresnia** [ocrdu/Arduino_SAMD21_Audio_Player#2]
Is it possible to recover samples from data structures other than const uint8_t ?
Because it tries to play samples from Flash memory on XIAO's SPI interface but it doesn't work.
You wrote a very nice library.
Sorry for my English.
Regards Jan Czereśnia.

**Comment by ocrdu** [comment]
No, the library only plays raw, mono, 8-bit samples, as in the example. It should be possible to add other formats, but I am not going to implement that. Feel free, though 8-).
